"""Vote model created

Revision ID: 40a451af4ff9
Revises: c444f6a547ba
Create Date: 2023-11-22 12:52:04.999063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a451af4ff9'
down_revision = 'c444f6a547ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'voter', ['voter_id'], ['usn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'voter', ['voter_id'], ['id'])

    # ### end Alembic commands ###
