"""Voter with usn added to Vote

Revision ID: 6c0c5dbc9dbe
Revises: 40a451af4ff9
Create Date: 2023-11-22 12:57:43.359728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0c5dbc9dbe'
down_revision = '40a451af4ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'voter', ['voter_id'], ['usn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'voter', ['voter_id'], ['id'])

    # ### end Alembic commands ###
