"""Made Creator to be NULLABLE

Revision ID: 880de3def10e
Revises: c7ad2c10e8a0
Create Date: 2023-11-22 11:59:37.646260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880de3def10e'
down_revision = 'c7ad2c10e8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
